server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway  # 服务名称
  cloud:
    nacos:
#      server-addr: localhost:8848 # nacos地址
      server-addr: nacos:8848 # nacos地址
    gateway:
      routes:  # 网关路由配置
        - id: user-service  # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://userService # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates:  # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/**  # 这个是按照路径匹配，只要以/user/开头就符合要求
          filters:
            - AddRequestHeader=Truth, HanyuYe will finally succeed! # 针对部分路由过滤器
        - id: order-service
          uri: lb://orderService
          predicates:
            - Path=/order/**
      # 过滤器优先级：看order值，order值一样时：default《局部routes《全局过滤器
      default-filters: # 针对所有路由过滤器：默认过滤项，注意：如果routes下有配置过滤器（filter中添加了请求头），会被routes中覆盖，全局则不起作用
        - AddRequestHeader=Truth, Itcast is freaking awesome!
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:5500"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
